import _ from "lodash"

/**
 * 获取场景流程图数据
 */
const SCENES = {
    storm: {
        nodes: [
            {
                id: "n1",
                text: "开始",
                type: "round",
                x: 200,
                y: 0,
                w: 0,
                h: 0,
                evt: "开始",
                use: true,
                disable: false,
            },
            {
                id: "n2",
                text: "信息监视",
                type: "square",
                x: 200,
                y: 80,
                w: 0,
                h: 0,
                evt: "信息监视",
                use: false,
                disable: false,
            },
            {
                id: "n3",
                text: "影响级别",
                type: "polygon",
                x: 180,
                y: 160,
                w: 140,
                h: 80,
                evt: "影响级别",
                use: false,
                disable: false,
            },
            {
                id: "n4",
                text: "应急会商",
                type: "square",
                x: 200,
                y: 300,
                w: 100,
                h: 40,
                evt: "应急会商",
                use: false,
                disable: false,
                assists: ["n8"]
            },
            {
                id: "n5",
                text: "方案确认",
                type: "square",
                x: 200,
                y: 380,
                w: 100,
                h: 40,
                evt: "方案确认",
                use: false,
                disable: false,
            },
            {
                id: "n6",
                text: "应急处置",
                type: "square",
                x: 200,
                y: 460,
                w: 100,
                h: 40,
                evt: "应急处置",
                use: false,
                disable: false,
            },
            {
                id: "n7",
                text: "方案终止判断",
                type: "polygon",
                x: 180,
                y: 560,
                w: 140,
                h: 80,
                evt: "方案终止判断",
                use: false,
                disable: false,
            },
            {
                id: "n8",
                text: "监管 监视",
                type: "square",
                x: 400,
                y: 400,
                w: 100,
                h: 40,
                evt: "监管 监视",
                use: false,
                disable: false,
            },
            {
                id: "n9",
                text: "统计数据\n撰写简报",
                type: "square",
                x: 200,
                y: 700,
                w: 100,
                h: 40,
                evt: "统计数据\n撰写简报",
                use: false,
                disable: false,
            },
            {
                id: "n10",
                text: "结束",
                type: "round",
                x: 200,
                y: 800,
                w: 100,
                h: 40,
                evt: "结束",
                use: false,
                disable: false,
            },
        ],
        links: [
            {
                id: "r1",
                source: "n1",
                target: "n2",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r2",
                source: "n2",
                target: "n3",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r3",
                source: "n3",
                target: "n4",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [
                    {
                        text: "等级高: 需要协同处置",
                        position: 0.5,
                    },
                ],
                use: false,
            },
            {
                id: "r4",
                source: "n4",
                target: "n5",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r5",
                source: "n5",
                target: "n6",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r6",
                source: "n6",
                target: "n7",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r7",
                source: "n7",
                target: "n9",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [
                    {
                        text: "是",
                        position: 0.5,
                    },
                ],
                use: false,
            },
            {
                id: "r8",
                source: "n9",
                target: "n10",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r9",
                source: "n7",
                target: "n4",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [
                    { x: 100, y: 600 },
                    { x: 100, y: 320 },
                ],
                labels: [{ text: "否", position: 0.5 }],
                use: false,
            },
            {
                id: "r10",
                source: "n3",
                target: "n8",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [{ x: 450, y: 200 }],
                labels: [{ text: "等级低: 自行处置", position: 0.6 }],
                use: false,
            },
            {
                id: "r11",
                source: "n8",
                target: "n9",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [
                    {
                        x: 445,
                        y: 720,
                    },
                ],
                labels: [],
                use: false,
            },
        ],
    },
    majorevent: {
        nodes: [
            {
                id: "n1",
                text: "开始",
                type: "round",
                x: 200,
                y: 0,
                w: 0,
                h: 0,
                evt: "开始",
                use: true,
                disable: false,
            },
            {
                id: "n2",
                text: "客流监控",
                type: "square",
                x: 200,
                y: 80,
                w: 0,
                h: 0,
                evt: "客流监控",
                use: false,
                disable: false,
            },
            {
                id: "n3",
                text: "影响评估",
                type: "polygon",
                x: 180,
                y: 160,
                w: 140,
                h: 80,
                evt: "影响评估",
                use: false,
                disable: false,
            },
            {
                id: "n4",
                text: "方案确认",
                type: "polygon",
                x: 180,
                y: 300,
                w: 140,
                h: 80,
                evt: "方案确认",
                use: false,
                disable: false,
            },
            {
                id: "n5",
                text: "运行图调整",
                type: "square",
                x: 300,
                y: 380,
                w: 100,
                h: 40,
                evt: "运行图调整",
                use: false,
                disable: false,
            },
            {
                id: "n6",
                text: "保障方案实施",
                type: "square",
                x: 200,
                y: 460,
                w: 100,
                h: 40,
                evt: "保障方案实施",
                use: false,
                disable: false,
            },
            {
                id: "n7",
                text: "方案结束判断",
                type: "polygon",
                x: 180,
                y: 560,
                w: 140,
                h: 80,
                evt: "方案结束判断",
                use: false,
                disable: false,
            },
            {
                id: "n8",
                text: "监管 监视",
                type: "square",
                x: 400,
                y: 450,
                w: 100,
                h: 40,
                evt: "监管 监视",
                use: false,
                disable: false,
            },
            {
                id: "n9",
                text: "统计数据\n撰写简报",
                type: "square",
                x: 200,
                y: 700,
                w: 100,
                h: 40,
                evt: "统计数据\n撰写简报",
                use: false,
                disable: false,
            },
            {
                id: "n10",
                text: "结束",
                type: "round",
                x: 200,
                y: 800,
                w: 100,
                h: 40,
                evt: "结束",
                use: false,
                disable: false,
            },
        ],
        links: [
            {
                id: "r1",
                source: "n1",
                target: "n2",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r2",
                source: "n2",
                target: "n3",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r3",
                source: "n3",
                target: "n4",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [
                    {
                        text: "等级高: 需要协同处置",
                        position: 0.5,
                    },
                ],
                use: false,
            },
            {
                id: "r4",
                source: "n4",
                target: "n5",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [
                    { x: 250, y: 400 }
                ],
                labels: [
                    {
                        text: "否",
                        position: 0.5,
                    },
                ],
                use: false,
            },
            {
                id: "r4-back",
                source: "n5",
                target: "n4",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [
                    { x: 350, y: 340 }
                ],
                labels: [],
                use: false,
            },
            {
                id: "r5",
                source: "n4",
                target: "n6",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [
                    {
                        text: "是",
                        position: 0.5,
                    },
                ],
                use: false,
            },
            {
                id: "r6",
                source: "n6",
                target: "n7",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r7",
                source: "n7",
                target: "n9",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [
                    {
                        text: "是",
                        position: 0.5,
                    },
                ],
                use: false,
            },
            {
                id: "r8",
                source: "n9",
                target: "n10",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r9",
                source: "n7",
                target: "n4",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [
                    { x: 100, y: 600 },
                    { x: 100, y: 340 },
                ],
                labels: [{ text: "否", position: 0.5 }],
                use: false,
            },
            {
                id: "r10",
                source: "n3",
                target: "n8",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [{ x: 450, y: 200 }],
                labels: [{ text: "等级低: 自行处置", position: 0.6 }],
                use: false,
            },
            {
                id: "r11",
                source: "n8",
                target: "n9",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [
                    {
                        x: 445,
                        y: 720,
                    },
                ],
                labels: [],
                use: false,
            },
        ],
    },
    daily: {
        nodes: [
            {
                id: "block",
                text: "",
                type: "square",
                x: 60,
                y: 0,
                w: 1,
                h: 1,
                evt: "开始",
                use: true,
                disable: false,
            },
            {
                id: "n1",
                text: "开始",
                type: "round",
                x: 200,
                y: 0,
                w: 0,
                h: 0,
                evt: "开始",
                use: true,
                disable: false,
            },
            {
                id: "n2",
                text: "选择线路",
                type: "square",
                x: 200,
                y: 80,
                w: 0,
                h: 0,
                evt: "选择线路",
                use: false,
                disable: false,
            },
            {
                id: "n3",
                text: "导入客流信息",
                type: "square",
                x: 200,
                y: 160,
                w: 0,
                h: 0,
                evt: "导入客流信息",
                use: false,
                disable: false,
            },
            {
                id: "n4",
                text: "选择交路方案",
                type: "square",
                x: 200,
                y: 240,
                w: 100,
                h: 40,
                evt: "选择交路方案",
                use: false,
                disable: false,
            },
            {
                id: "n5",
                text: "设计开行方案",
                type: "square",
                x: 200,
                y: 320,
                w: 100,
                h: 40,
                evt: "设计开行方案",
                use: false,
                disable: false,
            },
            {
                id: "n6",
                text: "铺画运行图",
                type: "square",
                x: 200,
                y: 400,
                w: 100,
                h: 40,
                evt: "铺画运行图",
                use: false,
                disable: false,
            },
            {
                id: "n7",
                text: "运行图校验",
                type: "polygon",
                x: 180,
                y: 560,
                w: 140,
                h: 80,
                evt: "运行图校验",
                use: false,
                disable: false,
            },
            {
                id: "n8",
                text: "运行图确认",
                type: "square",
                x: 200,
                y: 700,
                w: 100,
                h: 40,
                evt: "运行图确认",
                use: false,
                disable: false,
            },
            {
                id: "n9",
                text: "日常监控",
                type: "square",
                x: 200,
                y: 800,
                w: 100,
                h: 40,
                evt: "日常监控",
                use: false,
                disable: false,
            },
            {
                id: "n10",
                text: "结束",
                type: "round",
                x: 200,
                y: 900,
                w: 100,
                h: 40,
                evt: "结束",
                use: false,
                disable: false,
            },
        ],
        links: [
            {
                id: "r1",
                source: "n1",
                target: "n2",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r2",
                source: "n2",
                target: "n3",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r3",
                source: "n3",
                target: "n4",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r4",
                source: "n4",
                target: "n5",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r5",
                source: "n5",
                target: "n6",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r6",
                source: "n6",
                target: "n7",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r7",
                source: "n7",
                target: "n8",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [
                    {
                        text: "运行图无需调整",
                        position: 0.4
                    }
                ],
                use: false,
            },
            {
                id: "r7-1",
                source: "n8",
                target: "n9",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r8",
                source: "n9",
                target: "n10",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [],
                labels: [],
                use: false,
            },
            {
                id: "r9",
                source: "n7",
                target: "n6",
                sourcearrow: false,
                targetarrow: true,
                w: 0,
                h: 0,
                vertices: [
                    { x: 390, y: 600 },
                    { x: 390, y: 420 },
                ],
                labels: [{ text: "运行图需要调整", position: 0.5 }],
                use: false,
            },
        ],
    },
}


export function getFlowData(name) {
    if (SCENES[name]) {
        return _.cloneDeep(SCENES[name])
    }
    return [];
}

